srcDir = '/home/jason/Desktop/osqp_related/OSQP.m/src';
mklRoot = '/opt/intel/oneapi/mkl/latest';
includeDir = fullfile(mklRoot, 'include');
libRt = fullfile(mklRoot, 'lib', 'libmkl_rt.so');
mklLibDir = fileparts(libRt);
rpathFlag = ['LDFLAGS=$LDFLAGS -Wl,-rpath,' mklLibDir];

mex('-v', '-R2018a', ...
    ['-I' includeDir], ...
    "CFLAGS=$CFLAGS -Wall -Wextra -Werror=implicit-function-declaration", ...
    rpathFlag, ...
    fullfile(srcDir, 'pardiso_mkl_mex.c'), ...
    libRt, ...
    '-ldl', ...
    '-output', fullfile(srcDir, ['pardiso_mkl_mex.' mexext]));
